name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    if: ${{ contains(github.event.head_commit.message, 'build') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          rm -rf node_modules package-lock.json
          npm install --no-optional

      - name: Build project
        run: |
          cd frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/dist
          token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
